### PR TITLE
It.cfg editing (fonts_it directory missing)

### PR DESCRIPTION
**Pull request by KnuckleBuckle**

### CODE REVIEW

**Comment by vit9696** [comment]
Do you need specific fonts? If yes, then please also add a trailing newline to the file.

**Comment by KnuckleBuckle** [comment]
> Do you need specific fonts? If yes, then please also add a trailing newline to the file.

No, the fonts are the ones put in every standard version (since I looked that there wasn't the it.cfg in the scripts released like in the other languages, as I wrote in a mail a few days ago), and apparently every .cfg file has this directory. If it isn't needed, I'll delete the line right away.

**Comment by vit9696** [comment]
Fonts are used from fonts directory. If you need custom fonts, you add the `font-dir` line. If you do not need them, do not add the line.

**Comment by KnuckleBuckle** [comment]
> Fonts are used from fonts directory. If you need custom fonts, you add the `font-dir` line. If you do not need them, do not add the line.

Oh, then nevermind. Then I'll just refer to you the mail I've sent you a couple days ago for other details. You can delete the pull request if that line is unnecessary.

**Pull request closed without merging**
