### PR TITLE
More fixes for the servant issue (#3).

### PR DESCRIPTION
**Pull request by ooa113y**
I didn't catch all of them at first, sorry about that!
Pretty sure this time I got them!

Changed the one I missed in English, and figured I can apply this fix
to other languages as well because I'm almost completely certain that
the "R" transliteration doesn't work in any language at all and is just
a mistake on Witch-Hunt's part. I went for "Люнон" in Russian instead of
"Лунон" because it makes the connection to "Люцифер" clearer.

### CODE REVIEW

**Comment by vit9696** [comment]
Ugh, wait, is it not a change in the current Steam version? Because we have already been asked this question, and the issue with the names was that there was no source for us to choose one over the other.

**Comment by ooa113y** [comment]
Yeah, this change is from Steam, but as I previously explained it was made for a good reason (the names reference the seven stakes who later show up as servants in ep7). This is the only reason I'm suggesting it, really, the fact that it came from Steam is sorta irrelevant here.

**Comment by vit9696** [comment]
Right, ok. This makes sense to me, but there are many people involved here, so it may take some time to make a decision whether to apply this in all translations or only some. For now:

- I reverted #3, as it creates consistency issues, so please include its changes in this pull-request, so that we can merge altogether.
- I do not mind the changes in Russian translation.
- @knox-umineko does not mind the changes in English translation.
- We need confirmation for the Chinese translation. CC @AliasQli, @Asttear, @copyliu Please forward that to the right person.
- We need confirmation for the Brazilian Portuguese translation. CC @Monaco-a-Knox, @jackpot-666.

**Comment by Monaco-a-Knox** [comment]
If you change "Lunon/Lenon", then you should change "Asune/Berune" > "Asne/Belne".

I really hate Asne/Belne, that's why pt use R.

**Comment by ooa113y** [comment]
I don't think there's anything to gain from changing Asune to Asne, as far as references are concerned, though if we want to fully stick with that I'll make that change soon as well. As for the rest, well, I think it's unfortunately a matter of correctness rather than just preference, unlike many other translation differences between UP and WH, and the correct meaning should always be chosen.

**Comment by Monaco-a-Knox** [comment]
It's about consistency, all or nothing imo.
You can change English, but I'll keep "R" in Portuguese version. Thank you.

**Comment by copyliu** [comment]
As a result of preliminary discussions, we will remove the ruby annotate to `恋音` and so on in Chinese translation based on Japanese original text, but will be described in grimoire

**Comment by ooa113y** [comment]
I have undone the changes to Portugese and Chinese translations and applied the fix mentioned above. Unless there's anything else that needs to be done here, I believe this can now safely be merged.

**Comment by vit9696** [comment]
Looks good. Merged.

**Pull request merged**
