### PR TITLE
[WIP]replace grimoire with localized entries for specified language

### PR DESCRIPTION
**Pull request by copyliu**
for certain specified language (Chinese), it can replace all grimoire tags with localize files like 
```
`"............You've...`[gstg 1]
`been indulging in alcohol again, haven't you?"`[gstg 2]
`The old physician let out a sigh as he removed the stethoscope.`
```

### CODE REVIEW

**Comment by vit9696** [comment]
What do you plan to do with https://github.com/umineko-project/umineko-scripting/pull/2#issuecomment-581015964? I.e. the game state in gstg/gstc/gstt strongly depending on exact grimoire locations.

**Comment by copyliu** [comment]
this will replace #2, I think it's a more elegant solution

**Comment by copyliu** [comment]
> 
> 
> What do you plan to do with [#2 (comment)](https://github.com/umineko-project/umineko-scripting/pull/2#issuecomment-581015964)? I.e. the game state in gstg/gstc/gstt strongly depending on exact grimoire locations.

this PR do the following things
if language is `REPLACE_GRIM_WITH_LOCALIZE` (only cn here), remove all `gstg` tags from original scripts, and place `gstg` tags directly form `story/epX/lang/*.txt`

**Comment by vit9696** [comment]
Yes, I do not mind, just my only issue is whether we handle the compatibility issues in the next PR? If so, I can merge this…

**Comment by copyliu** [comment]
I think this PR will not affect non-Chinese languages, I will do more test later, if everything looks good, it can merged :)

**Comment by vit9696** [comment]
Sure, handle it yourself then.

**Pull request merged**
